### ISSUE TITLE
Slow loading before training

### ISSUE THREAD

**Issue by rohankhaire-work** [fastgs/FastGS#49]
Hello, thank you for your work.

I am on a 5090 RTX and it seems to take quite some time to load before the training begins. 
``` bash
CUDA_VISIBLE_DEVICES=0 OAR_JOB_ID=drjohnson python train.py -s ./datasets/db/drjohnson --eval --densification_interval 500  --optimizer_type default --test_iterations 30000  --highfeature_lr 0.0025 --grad_abs_thresh 0.0012 --dense 0.013 --mult 0.7
Optimizing
/root/miniconda3/envs/fastgs/lib/python3.7/site-packages/torch/cuda/__init__.py:146: UserWarning:
NVIDIA GeForce RTX 5090 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 compute_37.
If you want to use the NVIDIA GeForce RTX 5090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Output folder: ./output/drjohnson [23/04 07:14:23]Tensorboard not available: not logging progress [23/04 07:14:23]
Reading camera 263/263 [23/04 07:14:25]
Loading Training Cameras [23/04 07:14:25]
Loading Test Cameras [23/04 07:26:31]
Number of points at initialisation :  80861 [23/04 07:26:33]
Training progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30000/30000 [01:12<00:00, 413.21it/s, Loss=0.0236907]

[ITER 30000] Saving Gaussians [23/04 07:27:45]
Gaussian number: 250573 [23/04 07:27:47]
Training time: 70.8001393414298 [23/04 07:27:47]

Training complete. [23/04 07:27:47]
```

Could you help me out with problem? Thank you.

**Comment by Shiwei-Ren** [comment]
Hello! Thanks for your attention! From the terminal information you've shown, it seems that the issue lies in 'Loading Training Cameras [23/04 07:14:25] Loading Test Cameras [23/04 07:26:31]', which is quite strange! I'd like to know if you encounter this kind of issue when running the original [3DGS](https://github.com/graphdeco-inria/gaussian-splatting) algorithm on the same data?

**Comment by rohankhaire-work** [comment]
Hello @Shiwei-Ren 

I cloned the [3DGS](https://github.com/graphdeco-inria/gaussian-splatting) repo and ran the same dataset. here's the terminal output -

```bash
python train.py -s datasets/db/drjohnson/
Optimizing
Output folder: ./output/03952b55-a [24/04 08:36:10]
Tensorboard not available: not logging progress [24/04 08:36:10]
Reading camera 263/263 [24/04 08:36:10]
Converting point3d.bin to .ply, will happen only the first time you open the scene. [24/04 08:36:10]
Loading Training Cameras [24/04 08:36:10]
Loading Test Cameras [24/04 08:36:14]
Number of points at initialisation :  80861 [24/04 08:36:14]
Training progress:  17%|█████████████████▌                                                                                      | 5060/30000 [01:41<09:59, 41.64it/s, Loss=0.0509409, Depth Loss=0.0000000]
```

There's no loading problem here.

**Comment by Shiwei-Ren** [comment]
I re-downloaded the code and dataset, and the result is:
```bash
(fastgs) rensw@rensw:~/Downloads/FastGS$ CUDA_VISIBLE_DEVICES=0 OAR_JOB_ID=drjohnson python train.py -s /media/rensw/Lenovo/tandt_db/db/drjohnson --eval --densification_interval 500 --optimizer_type default --test_iterations 30000 --highfeature_lr 0.0025 --grad_abs_thresh 0.0012 --dense 0.013 --mult 0.7
Optimizing
Output folder: ./output/drjohnson [24/04 17:01:25]
Tensorboard not available: not logging progress [24/04 17:01:25]
Reading camera 263/263 [24/04 17:01:26]
Converting point3d.bin to .ply, will happen only the first time you open the scene. [24/04 17:01:26]
Loading Training Cameras [24/04 17:01:26]
Loading Test Cameras [24/04 17:01:31]
Number of points at initialization: 80861 [24/04 17:01:32]
Training progress: 31%|▌ | 9250/30000 [00:40<01:43, 199.58it/s, Loss=0.0364975]^CTraceback
```

The issue you mentioned earlier didn't occur. The GPU I’m using is the RTX 4070 Ti S.

**Comment by rohankhaire-work** [comment]
Hello @Shiwei-Ren 

Thank you for your help. I rebuild the environment with cuda 12.8 and resolved the illegal memory access problem by following this [issue](https://github.com/fastgs/FastGS/issues/7). Now it works properly.
